name: Docker CI/CD

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    name: Build, Scan & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Connexion Docker HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest -f azure-vote/Dockerfile .

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest
